name: jest
on: push

jobs:
  build:
    name: Sample-Check
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.5.0'
    - name: yarn install
      run: yarn install
    - name: Run Jest
      run: yarn test
    - name: Save test coverage artifact
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage